<script>
  import Attractions from "../../lib/components/Attractions.svelte";
  import Booking from "../../lib/components/Booking.svelte";
</script>

<section class="mt-[7.5rem] mb-52">
  <div class="mx-10 h-fill">
    <div class="flex flex-col gap-5 p-5 text-4xl rounded-lg bg-opacity-20 link-face bg-surface-500">
      <h1 class="text-6xl head">Dragon Sanctuary</h1>
      <p>We don't just offer a once in a lifetime chance of viewing these majestic monarchs, we also offer some attractions not found in any other corner of the universe.</p>
      <p>Take your time browsing what we have in store for you, dear visitor!</p>
      <p>Or, if you're only interested in the dragons, you can go ahead and book your visit!</p>
    </div>
    <div class="flex justify-around mt-10">
      <button type="btn" class="rounded-md btn variant-glass-surface">
        <a href="#book">Book your Trip</a>
      </button>
      <button type="btn" class="rounded-md btn variant-glass-surface">
        <a href="#attractions">Browse Attractions</a>
      </button>
    </div>
  </div>
</section>

<section id="attractions" class="static h-full">
 <Attractions />
</section>

<section id="book" class="h-full my-16">
  <div>
   <Booking />
  </div>
</section>

<style>
  .btn{
    -webkit-animation: vibrate-3 1.5s linear infinite alternate backwards;
	        animation: vibrate-3 1.5s linear infinite alternate backwards;

  }

  .head{
    -webkit-animation: text-shadow-pop-top 1.5s ease-in-out infinite alternate both;
	        animation: text-shadow-pop-top 1.5s ease-in-out infinite alternate both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2023-11-17 23:56:30
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-shadow-pop-top
 * ----------------------------------------
 */
@-webkit-keyframes text-shadow-pop-top {
  0% {
    text-shadow: 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555;
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
  100% {
    text-shadow: 0 -1px #555555, 0 -2px #555555, 0 -3px #555555, 0 -4px #555555, 0 -5px #555555, 0 -6px #555555, 0 -7px #555555, 0 -8px #555555;
    -webkit-transform: translateY(8px);
            transform: translateY(8px);
  }
}
@keyframes text-shadow-pop-top {
  0% {
    text-shadow: 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555, 0 0 #555555;
    -webkit-transform: translateY(0);
            transform: translateY(0);
  }
  100% {
    text-shadow: 0 -1px #555555, 0 -2px #555555, 0 -3px #555555, 0 -4px #555555, 0 -5px #555555, 0 -6px #555555, 0 -7px #555555, 0 -8px #555555;
    -webkit-transform: translateY(8px);
            transform: translateY(8px);
  }
}

  /* ----------------------------------------------
 * Generated by Animista on 2023-11-17 23:53:20
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation vibrate-3
 * ----------------------------------------
 */
@-webkit-keyframes vibrate-3 {
  0% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
  10% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  20% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  30% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(2px, 2px);
            transform: translate(2px, 2px);
  }
  50% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  70% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  80% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  90% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
}
@keyframes vibrate-3 {
  0% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
  10% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  20% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  30% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  40% {
    -webkit-transform: translate(2px, 2px);
            transform: translate(2px, 2px);
  }
  50% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  60% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  70% {
    -webkit-transform: translate(-2px, 2px);
            transform: translate(-2px, 2px);
  }
  80% {
    -webkit-transform: translate(-2px, -2px);
            transform: translate(-2px, -2px);
  }
  90% {
    -webkit-transform: translate(2px, -2px);
            transform: translate(2px, -2px);
  }
  100% {
    -webkit-transform: translate(0);
            transform: translate(0);
  }
}

</style>